version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      
db_data:/var/lib/mysql

  api:
    build: .
    ports:
      
"5001:5001"
  environment:
    DATABASE_URL: mysql://user:password@db:3306/mydatabase
  depends_on:
db

volumes:
  db_data: